# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: PhotoManagerAPI
      run: dotnet restore PhotoManagerAPI.sln
    - name: Build
      working-directory: PhotoManagerAPI
      run: dotnet build PhotoManagerAPI.sln --no-restore
    - name: Test
      working-directory: PhotoManagerAPI
      run: dotnet test PhotoManagerAPI.sln --no-build --verbosity normal
